### ISSUE TITLE
when starting the axelar-core it generates some errors

### ISSUE THREAD

**Issue by rooiie** [axelarnetwork/axelarate-community#110]
2021-07-22T14:33:44Z INF New websocket connection module=rpc-server protocol=websocket remote=127.0.0.1:40456
2021-07-22T14:33:44Z INF Starting wsConnection service impl=wsConnection module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":40456,"Zone":""}
2021-07-22T14:33:44Z INF Connected tendermint client at http://localhost:26657 module=vald
2021-07-22T14:33:44Z INF Start listening to events module=vald
2021-07-22T14:33:44Z INF initiate connection to tofnd gRPC server: host.docker.internal:50051 module=vald
panic: failed to create tss manager: context deadline exceeded

goroutine 1 [running]:
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd/vald.createTSSMgr(0x22287c0, 0xc0012b2d80, 0xc001175ef0, 0x14, 0x18, 0xc000c6e9b8, 0xc000f1a7d0, 0x47, 0x0, 0x0, ...)
        /go/axelar/cmd/axelard/cmd/vald/start.go:263 +0x186
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd/vald.listen(0xc001175ef0, 0x14, 0x18, 0x2287aa8, 0xc000f36450, 0x1dc7cec, 0x6, 0x226def0, 0xc000de2bc0, 0x2270cf8, ...)
        /go/axelar/cmd/axelard/cmd/vald/start.go:176 +0x48a
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd/vald.GetValdCommand.func1(0xc000ee2780, 0xc000bf6280, 0x0, 0x4, 0x0, 0x0)
        /go/axelar/cmd/axelard/cmd/vald/start.go:117 +0xa95
github.com/spf13/cobra.(*Command).execute(0xc000ee2780, 0xc000bf6240, 0x4, 0x4, 0xc000ee2780, 0xc000bf6240)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e1a280, 0x0, 0x0, 0xc000d47680)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e1a280, 0xc000d47680, 0xd, 0x4000000000000000, 0x0)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/cmd/execute.go:36 +0x265
main.main()
        /go/axelar/cmd/axelard/main.go:70 +0x14f
2021-07-22T14:33:59Z ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":40456,"Zone":""}
2021-07-22T14:33:59Z INF Stopping wsConnection service impl={"Logger":{}} module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":40456,"Zone":""}
2021-07-22T14:33:59Z ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket

**Comment by rooiie** [comment]
after a while it will go further but it is a weird issue

**Comment by yasiryagi** [comment]
I see the same error 


panic: failed to create tss manager: context deadline exceeded

goroutine 1 [running]:
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd/vald.createTSSMgr(0x22287c0, 0xc000f4efc0, 0xc00135a918, 0x14, 0x18, 0xc00149e9b8, 0xc00051e910, 0x47, 0x0, 0x0, ...)
        /go/axelar/cmd/axelard/cmd/vald/start.go:263 +0x186
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd/vald.listen(0xc00135a918, 0x14, 0x18, 0x2287aa8, 0xc0005e8270, 0x1dc7cec, 0x6, 0x226def0, 0xc000c89b00, 0x2270cf8, ...)
        /go/axelar/cmd/axelard/cmd/vald/start.go:176 +0x48a
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd/vald.GetValdCommand.func1(0xc001015180, 0xc0005a2a80, 0x0, 0x4, 0x0, 0x0)
        /go/axelar/cmd/axelard/cmd/vald/start.go:117 +0xa95
github.com/spf13/cobra.(*Command).execute(0xc001015180, 0xc0005a2a40, 0x4, 0x4, 0xc001015180, 0xc0005a2a40)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000cecc80, 0x0, 0x0, 0xc000c849b0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000cecc80, 0xc000c849b0, 0xd, 0x4000000000000000, 0x0)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/cmd/execute.go:36 +0x265
main.main()
        /go/axelar/cmd/axelard/main.go:70 +0x14f

**Comment by ggutoski** [comment]
This issue is old so I assume it is no longer relevant.  Feel free to re-open if it happens again.
