### ISSUE TITLE
Bitcoin Node errors

### ISSUE THREAD

**Issue by iamnathanwindsor** [axelarnetwork/axelarate-community#111]
My axelarate-community/c2d2/config.toml file reads:

`[bitcoin]
rpc_addr = "http://axelar:Ch91wtRPZhCjKF7OLXkF@bitcoin-node.testnet.axelar.dev:8332"`

I updated the community package version to v0.3.1 and then removed the old config.toml file, but when I run

`c2d2cli transfer satoshi 0xfEB31fe1edF6F53e37dd318c9467FdD783422ec0 --source-chain bitcoin --dest-chain ethereum --gas=auto --gas-adjustment=1.4`

I get this error:

`Error: failed to get bitcoin bridge client: unexpected error when waiting for bitcoin node warmup: Post "http://a6f628019c4194ded9623daaa54834e0-632184776.us-east-2.elb.amazonaws.com:8332": dial tcp: lookup a6f628019c4194ded9623daaa54834e0-632184776.us-east-2.elb.amazonaws.com on 192.168.65.5:53: no such host: connection to the bitcoin node failed
failed to get bitcoin bridge client: unexpected error when waiting for bitcoin node warmup: Post "http://a6f628019c4194ded9623daaa54834e0-632184776.us-east-2.elb.amazonaws.com:8332": dial tcp: lookup a6f628019c4194ded9623daaa54834e0-632184776.us-east-2.elb.amazonaws.com on 192.168.65.5:53: no such host: connection to the bitcoin node failed [axelarnetwork/axelar-core@v0.4.1-0.20210630015643-223d8277edbe/cmd/axelard/cmd/vald/btc/rpc/rpcClient.go:143]`

On the daemon, I run:
`join/joinTestnet.sh --tofnd v0.4.0 --axelar-core v0.5.1`

and I get this error, but then it skips it and seems to mine blocks.

`ERR Error dialing seed err="auth failure: conn.ID (0f8b5a12c59040ab9973d17bd8ddc21ce8b15e0b) dialed ID (6e09ca649a15daeaa97f14100cb95f062257bdd8) mismatch" module=p2p seed={"id":"6e09ca649a15daeaa97f14100cb95f062257bdd8","ip":"3.140.154.113","port":26656}
2021-07-22T22:48:40Z ERR Couldn't connect to any seeds module=p2p`

**Comment by ggutoski** [comment]
This issue is old so I assume it is no longer relevant. Feel free to re-open if it happens again.
