### ISSUE TITLE
EX2 || C2D2 || Error: failed to confirm withdrawal: failed to get transaction by hash: transaction type not supported

### ISSUE THREAD

**Issue by WayneWayner** [axelarnetwork/axelarate-community#119]
**Describe the bug**
Exercise 2 - Burn ERC20 wrapped Bitcoin tokens and obtain native Satoshi
When the burn transaction is detected, an error occurs stating that the transaction type is not supported. It is therefore not possible for the CLI to retrieve the 30 confirmations. This is an EIP-1559 transaction.

**To Reproduce**

1. Start with fresh system.
2. Complete prerequisite of exercise 2
3. Complete EX2 until **Burn ERC20 wrapped Bitcoin tokens and obtain native Satoshi**
4. Start **Burn ERC20 wrapped Bitcoin tokens and obtain native Satoshi** by typing in for example `c2d2cli transfer satoshi tb1qn267dum8dvgudl4u7x7dpk6uts9k5pc5cv8d3u --source-chain ethereum --dest-chain bitcoin --gas=auto --gas-adjustment=1.4`
5. Transfer satoshi to the provided ethereum address with **Metamask**
6. **ERROR**

**Expected behavior**
After the tx got recognized it should start analyzing the confirmations. 

**Screenshots/Log excerpts**

> bash-5.1# c2d2cli transfer satoshi tb1qn267dum8dvgudl4u7x7dpk6uts9k5pc5cv8d3u --source-chain ethereum --dest-chain bitcoin --gas=auto --gas-adjustment=1.4
>   | Using AxelarGateway at 0x2A1165BA03e10F2ce86c011f7771b9fA11f26274
>   | Using satoshi token at 0x817CB378496E5dA59b7D56ae0C91E89B19E821cE
> 
> info:    (3/5) Confirming Ethereum tx 0x43e8db8bd314d8e919be6c7a304db4c647e9fbcdb450aa68c9334035034d8296 on Axelar
> 
>   | ✗  0 of 30 required confirmations on Ethereum
> Error: failed to confirm withdrawal: failed to get transaction by hash: transaction type not supported
> failed to confirm withdrawal: failed to get transaction by hash: transaction type not supported [/build/pkg/bridges/evm/provider/client.go:219]

**Additional context**
Burn tx: https://ropsten.etherscan.io/tx/0x43e8db8bd314d8e919be6c7a304db4c647e9fbcdb450aa68c9334035034d8296

**Setup**
Bitcoin Wallet: Electrum Testnet
ETH Wallet: Metamask
Hardware: Bare metal server (Hetzner AX101)
OS: Ubuntu-2004-focal-64-minimal

**Comment by cgorenflo** [comment]
Thanks for the report. We are currently completely rewriting c2d2 so we won't issue an immediate fix for this, but we'll make sure the new version is going to play nice with EIP-1559 transactions. I will leave this issue open to inform on the progress once we've deployed the new version.

**Comment by kinrokinro** [comment]
Same
Tx hash: https://ropsten.etherscan.io/tx/0x240c9870d4035c5a8b0ff5df3e4271ad9d0572a99e8e1574b0f53710c6f096f3

**Comment by ggutoski** [comment]
Closed.  This issue is old so I assume it has been fixed. Feel free to re-open if need be.
