### ISSUE TITLE
join-testnet.sh fails due to placeholder RPC endpoints for bitcoin and ethereum

### ISSUE THREAD

**Issue by Windforcer** [axelarnetwork/axelarate-community#213]
**Describe the bug**
Running join-testnet.sh on main branch fails because the bitcoin and ethereum node RPC endpoints have changed, we replaced the axelar-run RPC endpoints with placeholders that are invalid RPC endpoints.

**To Reproduce**
checkout axelarate community main branch
run join/join-testnet.sh
fails due to error

**Expected behavior**
Using the placeholder RPC endpoint should not cause a regular axelar node to fail. For validator nodes, the expected behavior is uncertain due to changes to the bitcoin module support, and the ability to register as a chain maintainer for voting, in the next testnet release

A suitable, more descriptive error message should be logged

**Additional context**
see https://github.com/axelarnetwork/axelarate-community/issues/210 for a similar issue, caused by invalid configuration in the  config.toml

**Comment by Windforcer** [comment]
see https://github.com/axelarnetwork/axelarate-community/pull/212 for the PR for adding placeholder RPC endpoints

**Comment by ggutoski** [comment]
Need to fix this soon.  New testnet participants keep hitting it. (They're supposed to be on `v0.6.0` not `main`.)  I tried to fix it by replacing `"<your-ethereum-rpc>"` with the empty string `""` but I still got the error
```
unable to upgrade to tcp, received 500
```
My local system is all messed up due to multiple devnets/testnets and I don't have time to fix right now.  Can anyone else take a look?

**Comment by talalashraf** [comment]
https://github.com/axelarnetwork/axelar-core/commit/0c2b18c70545294ab9b6174b1a6e4800d8fec80e

**Comment by talalashraf** [comment]
joao did this !
