### ISSUE TITLE
update docs: solution to "too many open files" when syncing a node

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/axelarate-community#257]
Need to write a proper doc for "common problems and their solutions".  No time for that now so pasting rough notes here instead.

On node startup, node immediately shuts down with log:
```
panic: can't get node FCAA20B905AE004A69C12B3F17E88B8817FD73B10CB3586F1C87AF8B0E9FECC7: open /Users/gus/.axelar_testnet/.core/data/application.db/077294.ldb: too many open files
```

Fix: Mac OS has a very low limit on the concurrent open file handles. I increased it with `ulimit -n 2048`.

See https://github.com/cosmos/cosmos-sdk/issues/1394

**Comment by milapsheth** [comment]
Fixed by #293
