### ISSUE TITLE
Need to delete docker containers in order to restart a node

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/axelarate-community#290]
**Describe the bug**
Stop a healthy node and restart via `node.sh` and you see
```
docker: Error response from daemon: Conflict. The container name "/axelar-core" is already in use by container "f28510a0bfafd5d8ddae39d4205412b98dbb4befa23c8077fb921e14290a57ed". You have to remove (or rename) that container to be able to reuse that name.
```

**To Reproduce**
***Example***
1. Start with a healthy node.
2. `docker stop axelar-core`
3. Run `./scripts/node.sh` with appropriate flags

**Expected behavior**
Node should restart.

**Additional context**
I had to do `docker rm axelar-core` before step 3 to get `node.sh` to successfully start the node.

**Comment by milapsheth** [comment]
Fixed by #293
