### ISSUE TITLE
tBTC sent back to btc testnet is different than what i originally sent

### ISSUE THREAD

**Issue by mindstyle85** [axelarnetwork/axelarate-community#30]
**Describe the bug**

I am not sure if this is correct behaviour or not so i will just describe what i did. 

1. I minted 0.00087 tbtc and sent it all to ethereum
2. I then sent only 0.0004 tbtc back to bitcoin network here: https://ropsten.etherscan.io/tx/0x2d3cfba30d9b495b1d66bd147ff61725ab9437c747179040f91f5bed63498d78
3. After i confirmed, signed and submitted the tx via Blockcypher, i saw that it sent back the full 0.00087 tbtc somehow.. the tx for it is here: https://blockstream.info/testnet/tx/d19b75d38b626dacbb1fdba5ee29553d467ce2e1184a599e2da4c0b96e148f07

ETH addr: 0x2c2822031e9CAf1C031e71BB579fC796551F7BEE 
BTC addr: tb1qwe68q8zwdlhky2eg54a9cnlh7pmypgaqqnwne7fthjhthxl6x6zsgddvsg

**Comment by mindstyle85** [comment]
just to note that due to me doing transactions that were not mine (confirming other that were stuck), the point 3 actually isnt my address. It was a generated tx from another address/deposit which prevented me from finishing my own flow

**Comment by cgorenflo** [comment]
Thanks for reporting it. 
This is expected behaviour. The bitcoin transaction only consolidated the deposit into another address owned by axelar, it was not withdrawn.
