### ISSUE TITLE
Non default laddr port configuration setting seems to be ignored when using node.sh script

### ISSUE THREAD

**Issue by staketartare** [axelarnetwork/axelarate-community#347]
I'm trying to run an Axelar node on a non standard port

config.toml under both /home/axelar/.axelar_testnet/config and /home/axelar/.axelar/config has the following section:

```
[p2p]
# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26556"
```

(26556 instead of 26656 that is already used for another project)

But when I launch the node:
`./scripts/node.sh -e host -a v0.13.6 -n testnet -d /home/axelar/.axelar_testnet
`
I get:
```
2022-02-24T23:44:23+01:00 INF Starting Node service impl=Node
2022-02-24T23:44:23+01:00 INF Starting pprof server laddr=localhost:6060
2022-02-24T23:44:23+01:00 ERR pprof server error err="listen tcp 127.0.0.1:6060: bind: address already in use"
Error: listen tcp 0.0.0.0:26656: bind: address already in use
2022-02-24T23:44:23+01:00 INF Starting RPC HTTP server on [::]:26657 module=rpc-server

```

**Comment by staketartare** [comment]
I figured it out looking at the code.

It seems like the config is both duplicated under /home/axelar/.axelar_testnet/config and /home/axelar/.axelar_testnet/.core/config. The latter being the one that comes into effect.

Maybe it's a migration thing? Leaving open just in case there is something to clean up here.

**Comment by staketartare** [comment]
Running the node.sh script seems to reset the config under .core/config though and undo my changes.

What's the recommended approach to start the node on a different port?

Thanks

**Comment by ggutoski** [comment]
Thanks for the issue! ❤️ 

`node.sh` overwrites your config with whatever's in the `axelarate-community/configuration/config.toml`.  Any config change you want to persist after use of `node.sh` should be put in there.

Please do let us know if there's still a bug with custom ports.  Otherwise feel free to close this issue.

**Comment by staketartare** [comment]
Cool I should be able to make it work by editing `axelarate-community/configuration/config.toml` but it's kinda weird that the standard way to start the node always overwrites the config in place? 
It feels like overwritting the config with default config should be only happening with a special parameter no?
Cheers!

**Comment by ggutoski** [comment]
Agreed.  We need to overhaul and simplify the join scripts.  I've opened a new issue #355 for this.  Closing this issue.
