### ISSUE TITLE
a few comments on the "join validator" exercise: 

### ISSUE THREAD

**Issue by sergeynog** [axelarnetwork/axelarate-community#84]
* add a sentence description what is the "broadcaster" and why we need to register it. "Axelar network propagates messages from threshold multi-party computation protocols via the underlying consensus. Such messages are signed and delivered via the blockchain". 
* I believe we need to faucet funds to the "validator" address also, not just broadcaster. 
* worth adding a note that the validator needs to have >= 0.5% of the delegated stake to participate in the consensus. users can check what's active by looking at the monitoring dashboard pinned in the discord testnet channel.
* add a command to delegate more stake to a validator. 
* add a command to check how much stake the validator has bonded. 
* "monkier" -> should ask the testnet users to specify something descriptive for their nodes there. 
* rename the exercise to "join" only (i.e. remove "leave" part out of the exercise name).

**Comment by Windforcer** [comment]
Will make these changes today

The validator address funding is done during the instructions in README.md which is a prerequisite step. I can add a reminder for this

**Comment by Windforcer** [comment]
- Add denomination explaination (CLI uses microaxltest while dashboard uses axltest)

**Comment by Windforcer** [comment]
Completed with [PR 85](https://github.com/axelarnetwork/axelarate-community/pull/85url)
