### ISSUE TITLE
axelarcli q account shows a wrong denom

### ISSUE THREAD

**Issue by sophoah** [axelarnetwork/axelarate-community#9]
**Describe the bug**
`axelarcli q account` shows a wrong denom `stake`

see in full output
```
axelarcli keys show validator -a
axelar10vse7zu90ndfdw20vzelvxt8kjf7lf0uwt4cfu
/ # axelarcli q account axelar10vse7zu90ndfdw20vzelvxt8kjf7lf0uwt4cfu
{
  "type": "cosmos-sdk/Account",
  "value": {
    "address": "axelar10vse7zu90ndfdw20vzelvxt8kjf7lf0uwt4cfu",
    "coins": [
      {
        "denom": "stake",
        "amount": "1000000"
      }
    ],
    "public_key": {
      "type": "tendermint/PubKeySecp256k1",
      "value": "A8Vmg/1T+HY0IMcoNY5fBbrVlEupH+yLF4mvTxcT5fzV"
    },
    "account_number": "20",
    "sequence": "9"
  }
}
```

**To Reproduce**

1. Execute command `axelarcli keys show validator -a
axelar10vse7zu90ndfdw20vzelvxt8kjf7lf0uwt4cfu `

**Expected behavior**
Expected to have something different than the denom `stake`  maybe `axl` or whatever the team was planning to use

**Screenshots/Log excerpts**
If applicable, add screenshots or excerpts from the node log to help explain your problem.

**Additional context**

**Comment by haiyizxx** [comment]
Hi Sophoah, thanks for the report. Our team also noticed this issue and I am working on it. The change will be part of the next testnet iteration.

**Comment by haiyizxx** [comment]
The denom updated to `axltest`
